document.writeln("<footer>");
document.writeln("					<div class=\'wraper clearfix\'>");
document.writeln("						");
document.writeln("						<!-- 底部内容部分 -->");
document.writeln("						<div class=\'forus-footer\'>");
document.writeln("							<!-- 左侧内容 -->");
document.writeln("							<div class=\'foot-left left\'>");
document.writeln("								<img src=\'../img/logo.png\' >");
document.writeln("								<p>石家庄橙芽网络技术有限公司是一家专业专注于网络服务领域的高科技公司，作为一家以智能管理、网站开发为主的互联网技术公司，始终以领先的服务水平和技术实力，为各类企业客户提供顶尖的IT产品服务和技术解决方案</p>");

document.writeln("							</div>");
document.writeln("							");
document.writeln("							<!-- 右侧内容部分 -->");
document.writeln("							<div class=\'foot-right right\'>");
document.writeln("								<ul class=\'left\'>");
document.writeln("									<li>");
document.writeln("										<h4>快速入口</h4>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'../index.html\'>首页</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'project-case.html\'>项目案例</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'forus.html\'>关于我们</a>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<a href=\'service-introduction.html\'>服务介绍</a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("								<ul class=\'left\'>");
document.writeln("									<li>");
document.writeln("										<h4>联系方式</h4>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<p>电话： 000-0000-000</p>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<p>邮箱： 00000@00.000</p>");
document.writeln("									</li>");
document.writeln("									<li>");
document.writeln("										<p>地址： 石家庄市长安区嘉和广场4号写字楼25层</p>");
document.writeln("									</li>");
document.writeln("									");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("							");
document.writeln("							");
document.writeln("						</div>");
document.writeln("						<div class=\'di\'>");
document.writeln("							<p>@2019  石家庄橙芽网络技术有限公司 版权所有</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</footer>");