document.writeln("	<div class=\'header\'>");
document.writeln("				<div class=\'wraper\'>");
document.writeln("					<div class=\'header_left left\'></div>");
document.writeln("					<div class=\'header_right right\'>");
document.writeln("						<ul class=\'clearfix\'>");
document.writeln("							<li class=\'left\'>");
document.writeln("								<a href=\'../index.html\'>首页</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'left\'>");
document.writeln("								<a href=\'project-case.html\'>项目案例</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'left\'>");
document.writeln("								<a href=\'forus.html\'>关于我们</a>");
document.writeln("							</li>");
document.writeln("							<li class=\'left\'>");
document.writeln("								<a href=\'service-introduction.html\'>服务介绍</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");